// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      "type": "category",
      "label": "Foundamentals",
      "link": {
        "type": "generated-index",
        "description": "Kumo's Foundamentals develop!",
        "title": "Foundamentals"
      },
      "items": [
        {
          "type": "category",
          "label": "Performance Testing and Unit Testing",
          link: {
            "type": "doc",
            "id": "foundamentals/testing/index",
          },
          "items": [
            {
              "type": "category",
              "label": "doctest Unit Testing",
              "link": {
                "type": "generated-index",
                "description": "doctest Unit Testing",
                "title": "doctest Unit Testing"
              },
              "items": [
                "foundamentals/testing/doct/overview",
                "foundamentals/testing/doct/tutorial",
                "foundamentals/testing/doct/assertions",
                "foundamentals/testing/doct/testcases",
                "foundamentals/testing/doct/parameterized-tests",
                "foundamentals/testing/doct/logging",
                "foundamentals/testing/doct/commandline",
                "foundamentals/testing/doct/main",
                "foundamentals/testing/doct/configuration",
                "foundamentals/testing/doct/stringification",
                "foundamentals/testing/doct/reporters",
                "foundamentals/testing/doct/extensions",
                "foundamentals/testing/doct/faq",
                "foundamentals/testing/doct/build-systems",
                "foundamentals/testing/doct/benchmarks",
                "foundamentals/testing/doct/features"
              ]
            },
            {
              "type": "category",
              "label": "Google Test",
              "link": {
                "type": "generated-index",
                "description": "Kumo test",
                "title": "Kumo test"
              },
              "items": [
                "foundamentals/testing/gt/platforms",
                "foundamentals/testing/gt/quickstart-bazel",
                "foundamentals/testing/gt/quickstart-cmake",
                "foundamentals/testing/gt/primer",
                "foundamentals/testing/gt/advanced",
                "foundamentals/testing/gt/gmock_for_dummies",
                "foundamentals/testing/gt/gmock_cook_book",
                "foundamentals/testing/gt/gmock_cheat_sheet",
                "foundamentals/testing/gt/reference/testing",
                "foundamentals/testing/gt/reference/mocking",
                "foundamentals/testing/gt/reference/assertions",
                "foundamentals/testing/gt/reference/matchers",
                "foundamentals/testing/gt/reference/actions",
                "foundamentals/testing/gt/faq",
                "foundamentals/testing/gt/gmock_faq",
                "foundamentals/testing/gt/samples",
                "foundamentals/testing/gt/pkgconfig",
                "foundamentals/testing/gt/community_created_documentation"
              ]
            },
            {
              "type": "category",
              "label": "benchmark",
              link: {
                "type": "doc",
                "id": "foundamentals/testing/benchmark/index",
              },
              "items": [
                "foundamentals/testing/benchmark/AssemblyTests",
                "foundamentals/testing/benchmark/dependencies",
                "foundamentals/testing/benchmark/perf_counters",
                "foundamentals/testing/benchmark/platform_specific_build_instructions",
                "foundamentals/testing/benchmark/python_bindings",
                "foundamentals/testing/benchmark/random_interleaving",
                "foundamentals/testing/benchmark/reducing_variance",
                "foundamentals/testing/benchmark/releasing",
                "foundamentals/testing/benchmark/tools",
                "foundamentals/testing/benchmark/user_guide",
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Log Section',
          link: {
            "type": "doc",
            "id": "foundamentals/log/index",
          },
          items: [
            {
              "type": "category",
              "label": "get start",
              "link": {
                "type": "generated-index",
                "description": "using log！",
                "title": "starts"
              },
              "items": [
                "foundamentals/log/usage",
                "foundamentals/log/build",
                "foundamentals/log/packages"
              ]
            },
            {
              "type": "category",
              "label": "Log Tutorial",
              "link": {
                "type": "generated-index",
                "description": "log rutorial",
                "title": "Log Tutorial"
              },
              "items": [
                "foundamentals/log/logging",
                "foundamentals/log/sinks",
                "foundamentals/log/builtin_sinks",
                "foundamentals/log/flags"
              ]
            }

          ],
        },
        "foundamentals/time",
        {
          "type": "category",
          "label": "Standardized Errors and Error Return Values",
          "link": {
            "type": "generated-index",
            "description": "Standardize Kumo's error codes and return values!",
            "title": "Standardized Errors and Error Return Values"
          },
          "items": [
            "foundamentals/status/status-codes",
            "foundamentals/status/status"
          ]
        },
        {
          "type": "category",
          "label": "strings operations",
          link: {
            "type": "doc",
            "id": "foundamentals/strings/index",
          },
          "items": [
            "foundamentals/strings/fmt",
            "foundamentals/strings/split",
            "foundamentals/strings/strcat",
            "foundamentals/strings/join",
            "foundamentals/strings/substitution"
          ]
        },
        "foundamentals/flags",
        {
          "type": "category",
          "label": "Codec",
          link: {
            "type": "doc",
            "id": "foundamentals/codec/index",
          },
          "items": [
            "foundamentals/codec/base64",
          ]
        },
        "foundamentals/format/index",
        {
          "type": "category",
          "label": "Map Containers",
          link: {
            "type": "doc",
            "id": "foundamentals/map/index",
          },
          "items": [
            "foundamentals/map/turbo_hash",
            "foundamentals/map/concurrent_hash_map",
            "foundamentals/map/pmap",
            "foundamentals/map/benchmark",
          ]
        },
        {
          "type": "category",
          "label": "Compression",
          link: {
            "type": "doc",
            "id": "foundamentals/compress/index",
          },
          "items": [
            "foundamentals/compress/melon",
          ]
        },
        {
          "type": "category",
          "label": "Fiber And Future",
          link: {
            "type": "doc",
            "id": "foundamentals/fibers/index",
          },
          "items": [
            "foundamentals/fibers/futures",
            "foundamentals/fibers/std-future",
            "foundamentals/fibers/execution_queue",
            "foundamentals/fibers/kthread_schedule",
            "foundamentals/fibers/kthread_or_not",
            "foundamentals/fibers/faq",
          ]
        },
        {
          "type": "category",
          "label": "monitor",
          link: {
            "type": "doc",
            "id": "foundamentals/monitor/index",
          },
          "items": [
            "foundamentals/monitor/var",
            "foundamentals/monitor/metrics",
            "foundamentals/monitor/sys"
          ]
        },
        {
          "type": "category",
          "label": "filesystem",
          link: {
            "type": "doc",
            "id": "foundamentals/filesystem/index",
          },
          "items": [
            "foundamentals/filesystem/fs",
          ]
        },
        {
          "type": "category",
          "label": "json",
          link: {
            "type": "doc",
            "id": "foundamentals/json/index",
          },
          "items": [
            "foundamentals/json/overview",
            "foundamentals/json/features",
            "foundamentals/json/tutorial",
            "foundamentals/json/pointer",
            "foundamentals/json/stream",
            "foundamentals/json/encoding",
            "foundamentals/json/dom",
            "foundamentals/json/sax",
            "foundamentals/json/schema",
            "foundamentals/json/internals",
            "foundamentals/json/performance",
            "foundamentals/json/protobuf"
          ]
        },
      ]
    },
    {
      "type": "category",
      "label": "rpc",
      link: {
        "type": "doc",
        "id": "rpc/index",
      },
      "items": [
        "rpc/grpc",
        "rpc/brpc",
        "rpc/acl",
        "rpc/httplib",
        {
          "type": "category",
          "label": "krpc",
          "link": {
            "type": "generated-index",
            "description": "krcp docs!",
            "title": "krpc docs",
          },
          "items": [
            "rpc/krpc/getting_started",
            "rpc/krpc/server",
            "rpc/krpc/http_service",
            "rpc/krpc/thrift",
            "rpc/krpc/cpu_profiler",
            "rpc/krpc/heap_profiler",
            "rpc/krpc/contention_profiler",
            "rpc/krpc/dummy_server",
            "rpc/krpc/rpcz",
            "rpc/krpc/thread_local",
            "rpc/krpc/json2pb",
            "rpc/krpc/threading_overview",
            "rpc/krpc/atomic_instructions",
            "rpc/krpc/flags",
            "rpc/krpc/io",
            "rpc/krpc/streaming_rpc",
            "rpc/krpc/endpoint",
            "rpc/krpc/kumo_std",
            "rpc/krpc/client",
            "rpc/krpc/circuit_breaker",
            "rpc/krpc/connections",
            "rpc/krpc/lalb",
            "rpc/krpc/consistent_hashing",
            "rpc/krpc/http_client",
            "rpc/krpc/http_derivatives",
            "rpc/krpc/combo_channel",
            "rpc/krpc/memcache_client",
            "rpc/krpc/redis_client",
            "rpc/krpc/auto_concurrency_limiter",
            "rpc/krpc/server_debugging",
          ]
        },
      ]
    },
    {
      "type": "category",
      "label": "Retrieve",
      link: {
        "type": "doc",
        "id": "retrieve/index",
      },
      "items": [
        {
          "type": "category",
          "label": "bitmap",
          link: {
            "type": "doc",
            "id": "retrieve/bitmap/index",
          },
          "items": [
            "retrieve/bitmap/roaring",
          ]
        },
        {
          "type": "category",
          "label": "vector",
          link: {
            "type": "doc",
            "id": "retrieve/vector/index",
          },
          "items": [
            "retrieve/vector/faiss",
            "retrieve/vector/hnswlib",
            "retrieve/vector/nmslib",
            "retrieve/vector/ngt",
            "retrieve/vector/diskann",
            "retrieve/vector/sptag",
            "retrieve/vector/scann",
          ]
        },
        {
          "type": "category",
          "label": "trie",
          link: {
            "type": "doc",
            "id": "retrieve/trie/index",
          },
          "items": [
            "retrieve/trie/darts",
            "retrieve/trie/tsl",
            "retrieve/trie/marisa",
            "retrieve/trie/cedar",
          ]
        },
        {
          "type": "category",
          "label": "nlp",
          link: {
            "type": "doc",
            "id": "retrieve/nlp/index",
          },
          "items": [
            "retrieve/nlp/hadar",
            "retrieve/nlp/jieba",
            "retrieve/nlp/sentencepiece",
            "retrieve/nlp/stemming",
          ]
        },
        {
          "type": "category",
          "label": "regex",
          link: {
            "type": "doc",
            "id": "retrieve/regex/index",
          },
          "items": [
            "retrieve/regex/re2",
            "retrieve/regex/pcre",
          ]
        },
          "retrieve/post/index"
      ]
    },
    {
      "type": "category",
      "label": "store",
      link: {
        "type": "doc",
        "id": "store/index",
      },
      "items": [
        {
          "type": "category",
          "label": "kv",
          link: {
            "type": "doc",
            "id": "store/kv/index",
          },
          "items": [
            {
              "type": "category",
              "label": "rocksdb",
              "link": {
                "type": "generated-index",
                "description": "using rocksdb！",
                "title": "rocksdb"
              },
              "items": [
                "store/kv/rocksdb/overview",
                "store/kv/rocksdb/types",
                "store/kv/rocksdb/config",
                "store/kv/rocksdb/snapshot",
                "store/kv/rocksdb/backup",
                "store/kv/rocksdb/granite",
              ]
            },
            "store/kv/leveldb",
            "store/kv/lmdb",
          ]
        },
        {
          "type": "category",
          "label": "cloud",
          link: {
            "type": "doc",
            "id": "store/cloud/index",
          },
          "items": [
            "store/cloud/aws",
            "store/cloud/azure",
            "store/cloud/gcs",
            "store/cloud/hdfs",
          ]
        },
        {
          "type": "category",
          "label": "format",
          link: {
            "type": "doc",
            "id": "store/format/index",
          },
          "items": [
            "store/format/parquet",
            "store/format/hdf5",
            "store/format/ocr",
            "store/format/npy",
            "store/format/arrow",
            "store/format/avro",
            "store/format/substrait",
          ]
        },
      ]
    },
    {
      "type": "category",
      "label": "IR",
      link: {
        "type": "doc",
        "id": "ir/index",
      },
      "items": [
        "ir/ast",
        "ir/pegtl",
        "ir/bison-flex",
        "ir/antlr",
        "ir/llvm",
      ]
    },
    {
      "type": "category",
      "label": "advance",
      link: {
        "type": "doc",
        "id": "advance/index",
      },
      "items": [
        {
          "type": "category",
          "label": "ml",
          link: {
            "type": "doc",
            "id": "advance/ml/index",
          },
          "items": [
            "advance/ml/tensorflow",
            "advance/ml/pytorch",
            "advance/ml/onnx",
            "advance/ml/tvm",
            "advance/ml/codon",
            "advance/ml/ggml",
          ]
        },
        {
          "type": "category",
          "label": "compute",
          link: {
            "type": "doc",
            "id": "advance/compute/index",
          },
          "items": [
            "advance/compute/pollux",
            "advance/compute/arrow",
            "advance/compute/velox",
          ]
        },
        {
          "type": "category",
          "label": "gpu",
          link: {
            "type": "doc",
            "id": "advance/gpu/index",
          },
          "items": [
            "advance/gpu/cudnn",
          ]
        },
        {
          "type": "category",
          "label": "simd",
          link: {
            "type": "doc",
            "id": "advance/simd/index",
          },
          "items": [
            "advance/simd/distance",
          ]
        },
        {
          "type": "category",
          "label": "raft",
          link: {
            "type": "doc",
            "id": "advance/raft/index",
          },
          "items": [
            "advance/raft/algo",
          ]
        },
        {
          "type": "category",
          "label": "tensor",
          link: {
            "type": "doc",
            "id": "advance/tensor/index",
          },
          "items": [
            "advance/tensor/xtensor",
          ]
        },
      ]
    },
  ],
  integrationSidebar: [
    "integration/overview",
    {
      "type": "category",
      "label": "a-",
      "link": {
        "type": "generated-index",
        "description": "a start",
        "title": "a-"
      },
      "items": [
        "integration/abseil",
      ]
    },
    {
      "type": "category",
      "label": "b-",
      "link": {
        "type": "generated-index",
        "description": "b start",
        "title": "b-"
      },
      "items": [
        "integration/benchmark",
        "integration/boost",
        "integration/bzip2",
      ]
    },
    {
      "type": "category",
      "label": "c-",
      "link": {
        "type": "generated-index",
        "description": "c start",
        "title": "c-"
      },
      "items": [
        "integration/catch2",
        "integration/collie",
      ]
    },
    {
      "type": "category",
      "label": "d-",
      "link": {
        "type": "generated-index",
        "description": "d start",
        "title": "d-"
      },
      "items": [
        "integration/doctest",
      ]
    },
    {
      "type": "category",
      "label": "e-",
      "link": {
        "type": "generated-index",
        "description": "e start",
        "title": "e-"
      },
      "items": [
        "integration/eigen3",
      ]
    },
    {
      "type": "category",
      "label": "f-",
      "link": {
        "type": "generated-index",
        "description": "f start",
        "title": "f-"
      },
      "items": [
        "integration/fmt",
      ]
    },
    {
      "type": "category",
      "label": "g-",
      "link": {
        "type": "generated-index",
        "description": "g start",
        "title": "g-"
      },
      "items": [
        "integration/gflags",
        "integration/granite",
        "integration/gtest",
        "integration/ghc-filesystem",
      ]
    },
    {
      "type": "category",
      "label": "h-",
      "link": {
        "type": "generated-index",
        "description": "h start",
        "title": "h-"
      },
      "items": [
        "integration/hnswlib",
      ]
    },
    {
      "type": "category",
      "label": "i-",
      "link": {
        "type": "generated-index",
        "description": "i start",
        "title": "i-"
      },
      "items": [
        "integration/inih",
        "integration/inipp",
      ]
    },
    {
      "type": "category",
      "label": "j-",
      "link": {
        "type": "generated-index",
        "description": "j start",
        "title": "j-"
      },
      "items": [
        "integration/jemalloc",
      ]
    },
    {
      "type": "category",
      "label": "k-",
      "link": {
        "type": "generated-index",
        "description": "k start",
        "title": "k-"
      },
      "items": [
        "integration/kthread",
      ]
    },
    {
      "type": "category",
      "label": "l-",
      "link": {
        "type": "generated-index",
        "description": "l start",
        "title": "l-"
      },
      "items": [
        "integration/leveldb",
        "integration/lz4",
      ]
    },
    {
      "type": "category",
      "label": "m-",
      "link": {
        "type": "generated-index",
        "description": "m start",
        "title": "m-"
      },
      "items": [
        "integration/merak",
      ]
    },
    {
      "type": "category",
      "label": "n-",
      "link": {
        "type": "generated-index",
        "description": "n start",
        "title": "n-"
      },
      "items": [
        "integration/nlohmann-json",
      ]
    },
    {
      "type": "category",
      "label": "o-",
      "link": {
        "type": "generated-index",
        "description": "o start",
        "title": "o-"
      },
      "items": [
        "integration/openssl",
      ]
    },
    {
      "type": "category",
      "label": "p-",
      "link": {
        "type": "generated-index",
        "description": "p start",
        "title": "p-"
      },
      "items": [
        "integration/protobuf",
      ]
    },
    {
      "type": "category",
      "label": "r-",
      "link": {
        "type": "generated-index",
        "description": "r start",
        "title": "r-"
      },
      "items": [
        "integration/rocksdb",
        "integration/re2",
        "integration/roaring",
      ]
    },
    {
      "type": "category",
      "label": "s-",
      "link": {
        "type": "generated-index",
        "description": "s start",
        "title": "s-"
      },
      "items": [
        "integration/snappy",
      ]
    },
    {
      "type": "category",
      "label": "t-",
      "link": {
        "type": "generated-index",
        "description": "t start",
        "title": "t-"
      },
      "items": [
        "integration/tally",
        "integration/turbo",
      ]
    },
    {
      "type": "category",
      "label": "u-",
      "link": {
        "type": "generated-index",
        "description": "u start",
        "title": "u-"
      },
      "items": [
        "integration/utf8proc",
      ]
    },
    {
      "type": "category",
      "label": "v-",
      "link": {
        "type": "generated-index",
        "description": "v start",
        "title": "v-"
      },
      "items": [
        "integration/vamos",
      ]
    },
    {
      "type": "category",
      "label": "x-",
      "link": {
        "type": "generated-index",
        "description": "x start",
        "title": "x-"
      },
      "items": [
        "integration/xlog",
      ]
    },
    {
      "type": "category",
      "label": "y-",
      "link": {
        "type": "generated-index",
        "description": "y start",
        "title": "y-"
      },
      "items": [
        "integration/yaml-cpp",
      ]
    },

    {
      "type": "category",
      "label": "z-",
      "link": {
        "type": "generated-index",
        "description": "z start",
        "title": "z-"
      },
      "items": [
        "integration/zstd",
        "integration/zlib",
        "integration/zeromq",
      ]
    },

  ]
};


export default sidebars;
