// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      "type": "category",
      "label": "Foundamentals",
      "link": {
        "type": "generated-index",
        "description": "Kumo's Foundamentals develop!",
        "title": "Foundamentals"
      },
      "items": [
        {
          "type": "category",
          "label": "Performance Testing and Unit Testing",
          link: {
            "type": "doc",
            "id": "testing/index",
          },
          "items": [
            {
              "type": "category",
              "label": "doctest Unit Testing",
              "link": {
                "type": "generated-index",
                "description": "doctest Unit Testing",
                "title": "doctest Unit Testing"
              },
              "items": [
                "testing/doct/overview",
                "testing/doct/tutorial",
                "testing/doct/assertions",
                "testing/doct/testcases",
                "testing/doct/parameterized-tests",
                "testing/doct/logging",
                "testing/doct/commandline",
                "testing/doct/main",
                "testing/doct/configuration",
                "testing/doct/stringification",
                "testing/doct/reporters",
                "testing/doct/extensions",
                "testing/doct/faq",
                "testing/doct/build-systems",
                "testing/doct/benchmarks",
                "testing/doct/features"
              ]
            },
            {
              "type": "category",
              "label": "Google Test",
              "link": {
                "type": "generated-index",
                "description": "Kumo test",
                "title": "Kumo test"
              },
              "items": [
                "testing/gt/platforms",
                "testing/gt/quickstart-bazel",
                "testing/gt/quickstart-cmake",
                "testing/gt/primer",
                "testing/gt/advanced",
                "testing/gt/gmock_for_dummies",
                "testing/gt/gmock_cook_book",
                "testing/gt/gmock_cheat_sheet",
                "testing/gt/reference/testing",
                "testing/gt/reference/mocking",
                "testing/gt/reference/assertions",
                "testing/gt/reference/matchers",
                "testing/gt/reference/actions",
                "testing/gt/faq",
                "testing/gt/gmock_faq",
                "testing/gt/samples",
                "testing/gt/pkgconfig",
                "testing/gt/community_created_documentation"
              ]
            },
            {
              "type": "category",
              "label": "benchmark",
              link: {
                "type": "doc",
                "id": "testing/benchmark/index",
              },
              "items": [
                "testing/benchmark/AssemblyTests",
                "testing/benchmark/dependencies",
                "testing/benchmark/perf_counters",
                "testing/benchmark/platform_specific_build_instructions",
                "testing/benchmark/python_bindings",
                "testing/benchmark/random_interleaving",
                "testing/benchmark/reducing_variance",
                "testing/benchmark/releasing",
                "testing/benchmark/tools",
                "testing/benchmark/user_guide",
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Log Section',
          link: {
            "type": "doc",
            "id": "log/index",
          },
          items: [
            {
              "type": "category",
              "label": "get start",
              "link": {
                "type": "generated-index",
                "description": "using log！",
                "title": "starts"
              },
              "items": [
                "log/usage",
                "log/build",
                "log/packages"
              ]
            },
            {
              "type": "category",
              "label": "Log Tutorial",
              "link": {
                "type": "generated-index",
                "description": "log rutorial",
                "title": "Log Tutorial"
              },
              "items": [
                "log/logging",
                "log/sinks",
                "log/builtin_sinks",
                "log/flags"
              ]
            }

          ],
        },
        "time/time",
        {
          "type": "category",
          "label": "Standardized Errors and Error Return Values",
          "link": {
            "type": "generated-index",
            "description": "Standardize Kumo's error codes and return values!",
            "title": "Standardized Errors and Error Return Values"
          },
          "items": [
            "status/status-codes",
            "status/status"
          ]
        },
        {
          "type": "category",
          "label": "strings operations",
          link: {
            "type": "doc",
            "id": "strings/index",
          },
          "items": [
            "strings/fmt",
            "strings/split",
            "strings/strcat",
            "strings/join",
            "strings/substitution"
          ]
        },
        "flags/flags",
      ]
    },
  ],
  integrationSidebar: [
    "integration/overview",
    {
      "type": "category",
      "label": "a-",
      "link": {
        "type": "generated-index",
        "description": "a start",
        "title": "a-"
      },
      "items": [
        "integration/abseil",
      ]
    },
    {
      "type": "category",
      "label": "b-",
      "link": {
        "type": "generated-index",
        "description": "b start",
        "title": "b-"
      },
      "items": [
        "integration/benchmark",
        "integration/boost",
        "integration/bzip2",
      ]
    },
    {
      "type": "category",
      "label": "c-",
      "link": {
        "type": "generated-index",
        "description": "c start",
        "title": "c-"
      },
      "items": [
        "integration/catch2",
        "integration/collie",
      ]
    },
    {
      "type": "category",
      "label": "d-",
      "link": {
        "type": "generated-index",
        "description": "d start",
        "title": "d-"
      },
      "items": [
        "integration/doctest",
      ]
    },
    {
      "type": "category",
      "label": "e-",
      "link": {
        "type": "generated-index",
        "description": "e start",
        "title": "e-"
      },
      "items": [
        "integration/eigen3",
      ]
    },
    {
      "type": "category",
      "label": "f-",
      "link": {
        "type": "generated-index",
        "description": "f start",
        "title": "f-"
      },
      "items": [
        "integration/fmt",
      ]
    },
    {
      "type": "category",
      "label": "g-",
      "link": {
        "type": "generated-index",
        "description": "g start",
        "title": "g-"
      },
      "items": [
        "integration/gflags",
        "integration/granite",
        "integration/gtest",
        "integration/ghc-filesystem",
      ]
    },
    {
      "type": "category",
      "label": "h-",
      "link": {
        "type": "generated-index",
        "description": "h start",
        "title": "h-"
      },
      "items": [
        "integration/hnswlib",
      ]
    },
    {
      "type": "category",
      "label": "i-",
      "link": {
        "type": "generated-index",
        "description": "i start",
        "title": "i-"
      },
      "items": [
        "integration/inih",
        "integration/inipp",
      ]
    },
    {
      "type": "category",
      "label": "j-",
      "link": {
        "type": "generated-index",
        "description": "j start",
        "title": "j-"
      },
      "items": [
        "integration/jemalloc",
      ]
    },
    {
      "type": "category",
      "label": "k-",
      "link": {
        "type": "generated-index",
        "description": "k start",
        "title": "k-"
      },
      "items": [
        "integration/kthread",
      ]
    },
    {
      "type": "category",
      "label": "l-",
      "link": {
        "type": "generated-index",
        "description": "l start",
        "title": "l-"
      },
      "items": [
        "integration/leveldb",
        "integration/lz4",
      ]
    },
    {
      "type": "category",
      "label": "m-",
      "link": {
        "type": "generated-index",
        "description": "m start",
        "title": "m-"
      },
      "items": [
        "integration/merak",
      ]
    },
    {
      "type": "category",
      "label": "n-",
      "link": {
        "type": "generated-index",
        "description": "n start",
        "title": "n-"
      },
      "items": [
        "integration/nlohmann-json",
      ]
    },
    {
      "type": "category",
      "label": "o-",
      "link": {
        "type": "generated-index",
        "description": "o start",
        "title": "o-"
      },
      "items": [
        "integration/openssl",
      ]
    },
    {
      "type": "category",
      "label": "p-",
      "link": {
        "type": "generated-index",
        "description": "p start",
        "title": "p-"
      },
      "items": [
        "integration/protobuf",
      ]
    },
    {
      "type": "category",
      "label": "r-",
      "link": {
        "type": "generated-index",
        "description": "r start",
        "title": "r-"
      },
      "items": [
        "integration/rocksdb",
        "integration/re2",
        "integration/roaring",
      ]
    },
    {
      "type": "category",
      "label": "s-",
      "link": {
        "type": "generated-index",
        "description": "s start",
        "title": "s-"
      },
      "items": [
        "integration/snappy",
      ]
    },
    {
      "type": "category",
      "label": "t-",
      "link": {
        "type": "generated-index",
        "description": "t start",
        "title": "t-"
      },
      "items": [
        "integration/tally",
        "integration/turbo",
      ]
    },
    {
      "type": "category",
      "label": "u-",
      "link": {
        "type": "generated-index",
        "description": "u start",
        "title": "u-"
      },
      "items": [
        "integration/utf8proc",
      ]
    },
    {
      "type": "category",
      "label": "v-",
      "link": {
        "type": "generated-index",
        "description": "v start",
        "title": "v-"
      },
      "items": [
        "integration/vamos",
      ]
    },
    {
      "type": "category",
      "label": "x-",
      "link": {
        "type": "generated-index",
        "description": "x start",
        "title": "x-"
      },
      "items": [
        "integration/xlog",
      ]
    },
    {
      "type": "category",
      "label": "y-",
      "link": {
        "type": "generated-index",
        "description": "y start",
        "title": "y-"
      },
      "items": [
        "integration/yaml-cpp",
      ]
    },

    {
      "type": "category",
      "label": "z-",
      "link": {
        "type": "generated-index",
        "description": "z start",
        "title": "z-"
      },
      "items": [
        "integration/zstd",
        "integration/zlib",
        "integration/zeromq",
      ]
    },

  ]
};


export default sidebars;
